#!/usr/bin/env bash

main() {
    first_commit="$(git rev-list HEAD | tail -n 1)~"
    last_commit="HEAD"
    git filter-branch --env-filter '
        d="$(echo "$GIT_COMMITTER_DATE" | sed "s/T.*//")T00:00:00+00:00)"
        export GIT_COMMITTER_DATE="$d"
        export GIT_AUTHOR_DATE="$d"
    ' -f -- --all
}

main
