[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xbb9af7"
index = 17

[[colors.indexed_colors]]
color = "0x1d252c"
index = 18

[[colors.indexed_colors]]
color = "0x28323a"
index = 19

[[colors.indexed_colors]]
color = "0xb7c5d3"
index = 20

[[colors.indexed_colors]]
color = "0xf6f6f8"
index = 21

[colors.bright]
black = "0x526270"
blue = "0x7aa2f7"
cyan = "0x89ddff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xfbfbfd"
yellow = "0xb7c5d3"

[colors.cursor]
cursor = "0xd8e2ec"
text = "0x171d23"

[colors.normal]
black = "0x171d23"
blue = "0x7aa2f7"
cyan = "0x89ddff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xd8e2ec"
yellow = "0xb7c5d3"

[colors.primary]
background = "0x171d23"
foreground = "0xd8e2ec"

[cursor]
style = "Beam"

[font]
size = 11.0

[font.bold]
family = "Source Han Code JP"
style = "B"

[font.normal]
family = "Source Han Code JP"
style = "R"

[font.offset]
y = 1

[keyboard]
bindings = [
  # { key = "K",              mods = "Command", mode = ~Vi|~Search, chars = "\x0c"                 },
  # { key = "K",              mods = "Command", mode = ~Vi|~Search, action = ClearHistory          },
  # { key = "Key0",           mods = "Command",                    action = ResetFontSize         },
   { key = "+",         mods = "Command|Shift",                    action = "IncreaseFontSize"      },
   { key = "_",          mods = "Command|Shift",                    action = "DecreaseFontSize"      },
  # { key = "NumpadSubtract", mods = "Command",                    action = DecreaseFontSize      },
  # { key = "V",              mods = "Command",                    action = Paste                 },
  # { key = "C",              mods = "Command",                    action = Copy                  },
  # { key = "C",              mods = "Command", mode = Vi|~Search,  action = ClearSelection        },
  # { key = "H",              mods = "Command",                    action = Hide                  },
  # { key = "H",              mods = "Command|Alt",                action = HideOtherApplications },
  # { key = "M",              mods = "Command",                    action = Minimize              },
  # { key = "Q",              mods = "Command",                    action = Quit                  },
  # { key = "W",              mods = "Command",                    action = Quit                  },
  # { key = "N",              mods = "Command",                    action = SpawnNewInstance      },
  # { key = "F",              mods = "Command|Control",            action = ToggleFullscreen      },
  # { key = "F",              mods = "Command", mode = ~Search,     action = SearchForward         },
  # { key = "B",              mods = "Command", mode = ~Search,     action = SearchBackward        },
   { key = "{",              mods = "Command|Shift",              chars = "\u001B{"                },
   { key = "}",              mods = "Command|Shift",              chars = "\u001B}"                },
   { key = "A",              mods = "Command",                    chars = "\u001Ba"                },
   { key = "B",              mods = "Command",                    chars = "\u001Bb"                },
  #  { key = "C",              mods = "Command",                    chars = "\u001Bc"                },
   { key = "D",              mods = "Command",                    chars = "\u001Bd"                },
   { key = "E",              mods = "Command",                    chars = "\u001Be"                },
   { key = "F",              mods = "Command",                    chars = "\u001Bf"                },
   { key = "G",              mods = "Command",                    chars = "\u001Bg"                },
   { key = "H",              mods = "Command",                    chars = "\u001Bh"                },
   { key = "I",              mods = "Command",                    chars = "\u001Bi"                },
   { key = "J",              mods = "Command",                    chars = "\u001Bj"                },
   { key = "K",              mods = "Command",                    chars = "\u001Bk"                },
   { key = "L",              mods = "Command",                    chars = "\u001Bl"                },
   { key = "M",              mods = "Command",                    chars = "\u001Bm"                },
   { key = "N",              mods = "Command",                    chars = "\u001Bn"                },
   { key = "O",              mods = "Command",                    chars = "\u001Bo"                },
   { key = "P",              mods = "Command",                    chars = "\u001Bp"                },
  #  { key = "Q",              mods = "Command",                    chars = "\u001Bq"                },
   { key = "R",              mods = "Command",                    chars = "\u001Br"                },
  #  { key = "S",              mods = "Command",                    chars = "\u001Bs"                },
   { key = "T",              mods = "Command",                    chars = "\u001Bt"                },
   { key = "U",              mods = "Command",                    chars = "\u001Bu"                },
   # { key = "V",              mods = "Command",                    chars = "\u001Bv"                },
   { key = "W",              mods = "Command",                    chars = "\u001Bw"                },
   { key = "X",              mods = "Command",                    chars = "\u001Bx"                },
   { key = "Y",              mods = "Command",                    chars = "\u001By"                },
   { key = "Z",              mods = "Command",                    chars = "\u001Bz"                },
   { key = "A",              mods = "Command|Shift",              chars = "\u001BA"                },
   { key = "B",              mods = "Command|Shift",              chars = "\u001BB"                },
   { key = "C",              mods = "Command|Shift",              chars = "\u001BC"                },
   { key = "D",              mods = "Command|Shift",              chars = "\u001BD"                },
   { key = "E",              mods = "Command|Shift",              chars = "\u001BE"                },
   { key = "F",              mods = "Command|Shift",              chars = "\u001BF"                },
   { key = "G",              mods = "Command|Shift",              chars = "\u001BG"                },
   { key = "H",              mods = "Command|Shift",              chars = "\u001BH"                },
   { key = "I",              mods = "Command|Shift",              chars = "\u001BI"                },
   { key = "J",              mods = "Command|Shift",              chars = "\u001BJ"                },
   { key = "K",              mods = "Command|Shift",              chars = "\u001BK"                },
   { key = "L",              mods = "Command|Shift",              chars = "\u001BL"                },
   { key = "M",              mods = "Command|Shift",              chars = "\u001BM"                },
   { key = "N",              mods = "Command|Shift",              chars = "\u001BN"                },
   { key = "O",              mods = "Command|Shift",              chars = "\u001BO"                },
   { key = "P",              mods = "Command|Shift",              chars = "\u001BP"                },
   { key = "Q",              mods = "Command|Shift",              chars = "\u001BQ"                },
   { key = "R",              mods = "Command|Shift",              chars = "\u001BR"                },
   { key = "S",              mods = "Command|Shift",              chars = "\u001BS"                },
   { key = "T",              mods = "Command|Shift",              chars = "\u001BT"                },
   { key = "U",              mods = "Command|Shift",              chars = "\u001BU"                },
   { key = "V",              mods = "Command|Shift",              chars = "\u001BV"                },
   { key = "W",              mods = "Command|Shift",              chars = "\u001BW"                },
   { key = "X",              mods = "Command|Shift",              chars = "\u001BX"                },
   { key = "Y",              mods = "Command|Shift",              chars = "\u001BY"                },
   { key = "Z",              mods = "Command|Shift",              chars = "\u001BZ"                },
   { key = "Key1",           mods = "Command",                    chars = "\u001B1"                },
   { key = "Key2",           mods = "Command",                    chars = "\u001B2"                },
   { key = "Key3",           mods = "Command",                    chars = "\u001B3"                },
   { key = "Key4",           mods = "Command",                    chars = "\u001B4"                },
   { key = "Key5",           mods = "Command",                    chars = "\u001B5"                },
   { key = "Key6",           mods = "Command",                    chars = "\u001B6"                },
   { key = "Key7",           mods = "Command",                    chars = "\u001B7"                },
   { key = "Key8",           mods = "Command",                    chars = "\u001B8"                },
   { key = "Key9",           mods = "Command",                    chars = "\u001B9"                },
   { key = "Key0",           mods = "Command",                    chars = "\u001B0"                }
]

[scrolling]
history = 10000

[shell]
args = ["--login", "-c", "tmux a -t default || tmux new -s default"]
program = "/opt/homebrew/bin/bash"

[window]
decorations = "transparent"
opacity = 0.9

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 12
y = 10
